# Generated by Django 2.0.5 on 2018-05-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogReg', '0004_quotes_user_fav_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='user_fav_quote',
        ),
    ]
