# Generated by Django 2.0.5 on 2018-05-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applogReg', '0005_remove_quotes_user_fav_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='quote_fav_users',
        ),
        migrations.AddField(
            model_name='quotes',
            name='user_fav_quote',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fav_quotes', to='applogReg.Users'),
            preserve_default=False,
        ),
    ]
