# Generated by Django 2.0.5 on 2018-05-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogReg', '0006_auto_20180521_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='quote_fav_users',
            field=models.ManyToManyField(related_name='quote_fav_users', to='applogReg.Users'),
        ),
    ]
