# Generated by Django 2.0.5 on 2018-05-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogReg', '0007_quotes_quote_fav_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='quote_fav_users',
        ),
    ]
