# Generated by Django 2.0.5 on 2018-05-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applogReg', '0008_remove_quotes_quote_fav_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoutes', to='applogReg.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='user_fav_quote',
        ),
        migrations.AddField(
            model_name='join',
            name='users_fav_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_fav_quote', to='applogReg.Quotes'),
        ),
    ]
