# Generated by Django 2.0.5 on 2018-05-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applogReg', '0009_auto_20180521_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='user',
        ),
        migrations.AddField(
            model_name='quotes',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='qoutes', to='applogReg.Users'),
            preserve_default=False,
        ),
    ]
