# Generated by Django 2.0.5 on 2018-05-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applogReg', '0011_auto_20180521_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='users_fav_quote',
        ),
        migrations.AddField(
            model_name='join',
            name='user_fav_quotes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_fav_quotes', to='applogReg.Users'),
            preserve_default=False,
        ),
    ]
