# Generated by Django 2.0.5 on 2018-05-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applogReg', '0012_auto_20180521_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='user_fav_quotes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fav_quotes', to='applogReg.Quotes'),
        ),
    ]
