# Generated by Django 2.0.5 on 2018-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogReg', '0014_auto_20180521_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='quoted_by',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
