# Generated by Django 2.0.5 on 2018-05-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogReg', '0015_quotes_quoted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='user',
            field=models.ForeignKey(on_delete=False, related_name='quotes', to='applogReg.Users'),
        ),
    ]
